name: "Deploy - To Nexus On Github Release"
on:
  release:
    types: [released]

jobs:
  CI:
    uses: MOV-AI/.github/.github/workflows/frontend-workflow.yml@v1
    with:
      release: 'true'
    secrets:
      auto_commit_user: ${{ secrets.RAISE_BOT_COMMIT_USER }}
      auto_commit_mail: ${{ secrets.RAISE_BOT_COMMIT_MAIL }}
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      nexus_publisher_user: ${{ secrets.NEXUS_PUBLISHER_USR }}
      nexus_publisher_password: ${{ secrets.NEXUS_PUBLISHER_PWD }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      
